# Welcome to Jekyll!
#

# Site settings
title: Royal Cat Sitting
description: |
  Copyright Royal Cat Sitting 
owner: Royal Cat Sitting # or company name
first_published: 2023 # if migrating another site, the year of your first publish
email: royalcatsitting@hotmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.royalcatsitting.com" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  email: mailto:royalcatsitting@hotmail.com
  facebook-official: https://www.facebook.com/profile.php?id=100087165366215
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #flickr:
  instagram: https://www.instagram.com/royalcatsitting/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
